import React from "react";
import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { slide } from "@remotion/transitions/slide";
import { Scene1Hook } from "./scenes/Scene1Hook";
import { Scene2PriceAnchoring } from "./scenes/Scene2PriceAnchoring";
import { Scene3LossAversion } from "./scenes/Scene3LossAversion";
import { Scene4SmartShopper } from "./scenes/Scene4SmartShopper";
import { Scene5Reward } from "./scenes/Scene5Reward";
import { Scene6Brand } from "./scenes/Scene6Brand";
import { PSYCH_SCENES, PSYCH_TRANSITION } from "./tokens";

export const PsychologyVideo: React.FC = () => {
  return (
    <AbsoluteFill>
      {/* Voiceover — generated by GitHub Actions via ElevenLabs */}
      <Audio src={staticFile("voiceover-psychology.mp3")} volume={1} />

      <TransitionSeries>
        <TransitionSeries.Sequence durationInFrames={PSYCH_SCENES.hook}>
          <Scene1Hook />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition
          presentation={slide({ direction: "from-right" })}
          timing={linearTiming({ durationInFrames: PSYCH_TRANSITION })}
        />

        <TransitionSeries.Sequence durationInFrames={PSYCH_SCENES.priceAnchoring}>
          <Scene2PriceAnchoring />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition
          presentation={slide({ direction: "from-right" })}
          timing={linearTiming({ durationInFrames: PSYCH_TRANSITION })}
        />

        <TransitionSeries.Sequence durationInFrames={PSYCH_SCENES.lossAversion}>
          <Scene3LossAversion />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition
          presentation={slide({ direction: "from-right" })}
          timing={linearTiming({ durationInFrames: PSYCH_TRANSITION })}
        />

        <TransitionSeries.Sequence durationInFrames={PSYCH_SCENES.smartShopper}>
          <Scene4SmartShopper />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition
          presentation={fade()}
          timing={linearTiming({ durationInFrames: PSYCH_TRANSITION })}
        />

        <TransitionSeries.Sequence durationInFrames={PSYCH_SCENES.reward}>
          <Scene5Reward />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition
          presentation={fade()}
          timing={linearTiming({ durationInFrames: PSYCH_TRANSITION })}
        />

        <TransitionSeries.Sequence durationInFrames={PSYCH_SCENES.brand}>
          <Scene6Brand />
        </TransitionSeries.Sequence>
      </TransitionSeries>
    </AbsoluteFill>
  );
};
